github: [@your-username]
patreon: # Ссылка на Patreon
open_collective: # Ссылка на Open Collective
ko_fi: # Ссылка на Ko-fi
tidelift: # Ссылка на Tidelift
community_bridge: # Ссылка на Community Bridge
liberapay: # Ссылка на Liberapay
issuehunt: # Ссылка на IssueHund
otechie: # Ссылка на Otechie
custom: ['https://tvorogvpn.com/donate']